apps/quotes/urls.py
from django.conf.urls import url
from . import views

# This line is new!


urlpatterns = [
    url(r"^$", views.index, name="index"),
    url(r"^create/$", views.create, name="create"),
    url(r"^view/$", views.view, name="view"),
    url(r"^edit/(?P<quote_id>\d+)/$", views.edit, name="edit"),
    url(r"^update/(?P<quote_id>\d+)/$", views.update, name="update"),
    url(r"^delete/(?P<quote_id>\d+)/$", views.delete, name="delete"),
    url(r"^like/(?P<quote_id>\d+)/$", views.like, name="like"),
    url(r"^unlike/(?P<quote_id>\d+)/$", views.unlike, name="unlike"),
    url(r"^home/$", views.home, name="home"),
    url(r"^python/$", views.python, name="python"),
    url(r"^about/$", views.about, name="about"),
    url(r"^csharp/$", views.csharp, name="csharp"),
    url(r"^contact/$", views.contact, name="contact"),
]

apps/users/urls.py
from django.conf.urls import url
from . import views  # This line is new!


urlpatterns = [
    # url(r'^$', views.index, name="index")
    url(r"^new/$", views.new, name="new"),
    url(r"^create/$", views.create, name="create"),
    url(r"^login/$", views.login, name="login"),
    url(r"^logout/$", views.logout, name="logout"),
    # url(r'^show/(?P<user_id>\d+)/$', views.show, name="show"),# This line has changed! Notice that urlpatterns is a list, the comma is in
    url(r"^edit/(?P<user_id>\d+)/$", views.edit, name="edit"),
    url(r"^update/(?P<user_id>\d+)/$", views.update, name="update"),
    # url(r'^delete/(?P<user_id>\d+)/$', views.delete, name="delete")
]

quote_dash/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r"^admin/", admin.site.urls),
    url(r"^", include("apps.quotes.urls", namespace="quotes")),
    url(r"^users/", include("apps.users.urls", namespace="users")),
]

apps/users/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db import models
from django.contrib import messages
import bcrypt
import re


EMAIL_REGEX = re.compile(r"^[a-zA-Z0-9.+_-]+@[a-zA-Z0-9._-]+\.[a-zA-Z]+$")
# Create your models here.


class UserManager(models.Manager):
    def validate(self, form_data):
        errors = []

        if len(form_data["first_name"]) < 3:
            errors.append("First name must be at least 3 characters!")
        if len(form_data["last_name"]) < 3:
            errors.append("Last name must be at least 3 characters!")
        if len(form_data["email"]) < 3:
            errors.append("email must be at least 3 characters!")
        if not EMAIL_REGEX.match(form_data["email"]):
            errors.append("Invalid Email Address!")
        if len(form_data["password"]) < 8:
            errors.append("password must be at least 8 characters!")

        existing_users = self.filter(email=form_data["email"])
        if existing_users:
            errors.append("Email already in use")
        return errors

    def create_user(self, form_data):
        pw_hash = bcrypt.hashpw(form_data["password"].encode(), bcrypt.gensalt())
        return self.create(
            first_name=form_data["first_name"],
            last_name=form_data["last_name"],
            email=form_data["email"],
            pw_hash=pw_hash,
        )

    def login(self, form_data):
        existing_users = self.filter(email=form_data["email"])
        if not existing_users:
            return (False, "Email or password invalid")

        user = existing_users[0]
        if bcrypt.checkpw(form_data["password"].encode(), user.pw_hash.encode()):
            return (True, user)
        else:
            return (False, "Email or password invalid")

    def updateerror(self, form_data):
        errors = []

        if len(form_data["first_name"]) < 3:
            errors.append("First name must be at least 3 characters!")
        if len(form_data["last_name"]) < 3:
            errors.append("Last name must be at least 3 characters!")
        if len(form_data["email"]) < 3:
            errors.append("email must be at least 3 characters!")
        if not EMAIL_REGEX.match(form_data["email"]):
            errors.append("Invalid Email Address!")
        existing_users = self.filter(email=form_data["email"])
        if existing_users:
            errors.append("Email already in use")

        return errors

    def update(self, form_data, user_id):
        user = self.get(id=user_id)
        user.first_name = form_data["first_name"]
        user.last_name = form_data["last_name"]
        user.email = form_data["email"]
        user.save()


class User(models.Model):
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    email = models.CharField(max_length=255)
    pw_hash = models.CharField(max_length=500)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    objects = UserManager()

    def __repr__(self):
        return "<user: %s>" % self.first_name

    def __str__(self):
        return "<User: %s>" % self.first_name

apps/users/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from .models import User
from apps.quotes.models import Quote
from django.core.exceptions import ObjectDoesNotExist


# Create your views here.


def new(req):
    return render(req, "users/new.html")


def create(req):
    errors = User.objects.validate(req.POST)
    if errors:
        for error in errors:
            messages.error(req, error)
            return redirect("users:new")
    else:
        user = User.objects.create_user(req.POST)
        req.session["user_id"] = user.id
    return redirect("quotes:index")


def login(req):
    valid, result = User.objects.login(req.POST)
    if not valid:
        messages.error(req, result)
        return redirect("users:new")
    else:
        req.session["user_id"] = result.id
    return redirect("quotes:index")


def logout(req):
    req.session.clear()

    return redirect("users:new")


def edit(req, user_id):
    if "user_id" not in req.session:
        return redirect("users:new")

    try:
        context = {"user": User.objects.get(id=req.session["user_id"])}
        print(req.POST)
    except ObjectDoesNotExist:
        return redirect("quotes:index")

    return render(req, "users/edit.html", context)


def update(req, user_id):
    errors = User.objects.updateerror(req.POST)
    if errors:
        for error in errors:
            messages.error(req, error)
        return redirect("users:edit", user_id=user_id)
    User.objects.update(req.POST, user_id)
    return redirect("quotes:index")

apps/users/templates/users/edit.html
{% extends "quotes/base.html" %}

{% block title %}
Edit
{% endblock title %}



{% block content %}

<h1>Hello {{ user.first_name }}, Lets edit your Account </h1> <br>
<hr>
<a href="{% url 'users:logout' %}" class="button">
    <h4>Logout</h4>
</a>
<a href="{% url 'quotes:index'  %}" class="button">
    <h4>Goback</h4>
</a>
<hr>




{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}
<form action="{% url 'users:update' user.id%}" method='post'>
    {% csrf_token %}
    <div class="form-group">
        <p> <label for="first_name">First Name:</label> </p>
        <P> <input type="text" class="form-control" name="first_name" placeholder=" your frist name"
                value="{{ user.first_name }}">
        </p>
    </div>

    <div class="form-group">
        <p> <label for="last_name">Last Name:</label> </p>
        <P> <input type="text" class="form-control" name="last_name" placeholder=" your frist name"
                value="{{ user.last_name }}">
        </p>
    </div>

    <div class="form-group">
        <p> <label for="email">Email:</label> </p>
        <P> <input type="text" class="form-control" name="email" placeholder="whats your email"
                value="{{ user.email }}">
        </p>
    </div>


    <input class="form-control" type="submit" value="edit">



</form>

{% endblock content %}

apps/users/templates/users/new.html
{% extends "quotes/base.html" %}

{% block title %}
Login and Registration
{% endblock title %}



{% block content %}



<h1> SignUp or LogIn to Write your favourite Quote and its Author. </h1><br><br>
<hr>



<h1> Register:</h1><br>



{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
        {% endfor %}
</ul>
{% endif %}
<form action="/users/create/" method='post'>
    {% csrf_token %}
    <div class="form-group">
        <p> <label for="first_name">First Name:</label> </p>
        <P> <input type="text" class="form-control" name="first_name" placeholder="Please enter your first name">
        </p>
    </div>
    <div class="form-group">
        <p> <label for="last_name">Last Name:</label> </p>
        <p> <input type="text" class="form-control" name="last_name" placeholder="Please enter your last name">
        </p>
    </div>
    <div class="form-group">
        <p> <label for="email">Email:</label> </p>
        <p> <input type="text" class="form-control" name="email" placeholder="Please enter your email ">
            We'll never share your email with anyone else.</p>
    </div>
    <div class="form-group">
        <p> <label for="password">Password:</label> </p>
        <p> <input type="text" class="form-control" name="password" placeholder="password"> </p>
    </div>
    <div>
        <p> <input type="submit" value="Register"> </p>
    </div>
</form><br>
<hr>



<h1>Login</h1><br><br>
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
        {% endfor %}
</ul>
{% endif %}
<form action="/users/login/" method='post'>
    {% csrf_token %}
    <div class="form-group">
        <p> <label for="email">Email:</label> </p>
        <p> <input type="text" class="form-control" name="email" placeholder="Please enter you email ">
        </p>
    </div>
    <div class="form-group">
        <p> <label for="password">Password:</label> </p>
        <p> <input type="text" class="form-control" name="password" placeholder="password"> </p>
    </div>
    <div>
        <p> <input type="submit" value="Login"></p>
    </div>
</form>


{% endblock content %}