apps/quotes/urls.py
from django.conf.urls import url
from . import views

# This line is new!


urlpatterns = [
    url(r"^$", views.index, name="index"),
    url(r"^create/$", views.create, name="create"),
    url(r"^view/$", views.view, name="view"),
    url(r"^edit/(?P<quote_id>\d+)/$", views.edit, name="edit"),
    url(r"^update/(?P<quote_id>\d+)/$", views.update, name="update"),
    url(r"^delete/(?P<quote_id>\d+)/$", views.delete, name="delete"),
    url(r"^like/(?P<quote_id>\d+)/$", views.like, name="like"),
    url(r"^unlike/(?P<quote_id>\d+)/$", views.unlike, name="unlike"),
    url(r"^home/$", views.home, name="home"),
    url(r"^python/$", views.python, name="python"),
    url(r"^about/$", views.about, name="about"),
    url(r"^csharp/$", views.csharp, name="csharp"),
    url(r"^contact/$", views.contact, name="contact"),
]

apps/users/urls.py
from django.conf.urls import url
from . import views  # This line is new!


urlpatterns = [
    # url(r'^$', views.index, name="index")
    url(r"^new/$", views.new, name="new"),
    url(r"^create/$", views.create, name="create"),
    url(r"^login/$", views.login, name="login"),
    url(r"^logout/$", views.logout, name="logout"),
    # url(r'^show/(?P<user_id>\d+)/$', views.show, name="show"),# This line has changed! Notice that urlpatterns is a list, the comma is in
    url(r"^edit/(?P<user_id>\d+)/$", views.edit, name="edit"),
    url(r"^update/(?P<user_id>\d+)/$", views.update, name="update"),
    # url(r'^delete/(?P<user_id>\d+)/$', views.delete, name="delete")
]

quote_dash/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r"^admin/", admin.site.urls),
    url(r"^", include("apps.quotes.urls", namespace="quotes")),
    url(r"^users/", include("apps.users.urls", namespace="users")),
]

apps/quotes/models.py
from django.db import models
from ..users.models import User


# Create your models here.
class QuoteManager(models.Manager):
    def validate(self, form_data):
        errors = []

        if len(form_data["author"]) < 3:
            errors.append("author's name must be at least 3 characters long.")
        if len(form_data["quote"]) < 10:
            errors.append("quote must be more than 10 characters long. ")
        if len(form_data["quote"]) > 255:
            errors.append("quote must be less than 255 characters")

        return errors

    def create_quote(self, form_data, user_id):
        user = User.objects.get(id=user_id)
        Quote.objects.create(
            author=form_data["author"], quote=form_data["quote"], creator=user
        )

    def update(self, form_data, quote_id):
        quote = self.get(id=quote_id)
        quote.author = form_data["author"]
        quote.quote = form_data["quote"]
        quote.save()

    def add_like(self, user_id, quote_id):
        user = User.objects.get(id=user_id)
        quote = Quote.objects.get(id=quote_id)
        user.liked.add(quote)
        user.save()


    def remove_like(self, user_id, quote_id):
        user = User.objects.get(id=user_id)
        quote = Quote.objects.get(id=quote_id)
        user.liked.remove(quote)

class Quote(models.Model):
    author = models.CharField(max_length=255)
    quote = models.TextField(blank=True, null=True)
    posted_quote = models.BooleanField(default=False)
    likes = models.ManyToManyField(User, related_name="liked")
    creator = models.ForeignKey(User, related_name="quotes", on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    objects = QuoteManager()

    def __repr__(self):
        return "<User: %s>" % self.first_name

    def __str__(self):
        return "<User: %s>" % self.first_name

apps/quotes/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.db.models import Count
from .models import User
from .models import Quote
from django.core.exceptions import ObjectDoesNotExist


# Create your views here.


def index(req):
    if "user_id" not in req.session:
        return redirect("users:new")
    else:
        context = {
            "user": User.objects.get(id=req.session["user_id"]),
            "quotes": Quote.objects.order_by("-created_at"),
        }
        return render(req, "quotes/quotes.html", context)


def create(req):
    errors = Quote.objects.validate(req.POST)
    if errors:
        for error in errors:
            messages.error(req, error)
        return redirect("quotes:index")
    else:
        Quote.objects.create_quote(req.POST, req.session["user_id"])
        print(req.POST)
    return redirect("quotes:index")


def view(req):

    if "user_id" not in req.session:

        return redirect("users:new")

    else:
        user = User.objects.get(id=req.session["user_id"])
        context = {"user": user, "quotes": Quote.objects.all()}
    return render(req, "quotes/view.html", context)


def edit(req, quote_id):
    if "user_id" not in req.session:
        return redirect("users:new")

    try:
        context = {
            "user": User.objects.get(id=req.session["user_id"]),
            "quote": Quote.objects.get(id=quote_id),
        }
        print(req.POST)
    except ObjectDoesNotExist:
        return redirect("quotes:index")

    return render(req, "quotes/edit.html", context)


def update(req, quote_id):
    errors = Quote.objects.validate(req.POST)
    if errors:
        for error in errors:
            messages.error(req, error)
        return redirect("quotes:edit", quote_id=quote_id)
    Quote.objects.update(req.POST, quote_id)
    return redirect("quotes:index")


def delete(req, quote_id):
    try:
        quote = Quote.objects.get(id=quote_id)
        quote.delete()
    except ObjectDoesNotExist:
        print("TRIED TO DELETE Quote #{}, DOES NOT EXIST".format(quote_id))

    return redirect("quotes:index")


def like(req, quote_id):
    Quote.objects.add_like(req.session["user_id"], quote_id)
    return redirect("quotes:index")


def unlike(req, quote_id):
    Quote.objects.remove_like(req.session["user_id"], quote_id)
    return redirect("quotes:index")


def home(req):
    return redirect("http://http://18.220.137.34/")


def about(req):
    return redirect("http://http://18.220.137.34/about/")


def python(req):
    return redirect("http://http://18.220.137.34/python/")


def csharp(req):
    return redirect("http://http://18.220.137.34/csharp/")


def contact(req):
    return redirect("http://http://18.220.137.34/about/Pdf/")

apps/quotes/templates/quotes/base.html
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title> {% block title %}

        {% endblock title %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css"
        integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'quotes/css/style.css' %}" media="screen" title="no title" charset="utf-8">
    <style>
        body {
            background-color: dodgerblue;
            color: whitesmoke;
            width: auto;
            height: auto;

        }

        .container-fluid {
            background-color: deeppink;
            width: auto;
            height: auto;
            margin: 0px 160px 0px 160px;
            padding: 160px 40px 220px 40px;
            border: 0px solid whitesmoke;
            border-radius: 0px;


        }


        h4 {
            font-size: 33px;
        }


        @keyframes fadeInDown {
            from {
                opacity: 0;
                -webkit-transform: translate3d(0, -100%, 0);
                transform: translate3d(0, -100%, 0);
            }

            to {
                opacity: 1;
                -webkit-transform: translate3d(0, 0, 0);
                transform: translate3d(0, 0, 0);
            }
        }

        .fadeInDown {
            -webkit-animation-name: fadeInDown;
            animation-name: fadeInDown;
        }


        h2 {
            /* This section calls the slideInFromrightt animation we defined above */
            animation: 3s ease-out .7s 1 fadeInDown;
        }


        li {
            /* This section calls the slideInFromrightt animation we defined above */
            animation: 3s ease-out .5s 1 fadeInDown;
        }



        div.jumbotron {
            background-color: black;
            width: auto;
            height: auto;
            margin: auto;
            padding: 30px 0px 30px 0px;
            border-radius: 0px;
            font-family: monospace;
            font-size: 33px;

        }



        #header,
        Ul,
        li,
        h1 {
            display: inline-block;
            vertical-align: top;
            padding: 0px 0px 0px 10px;
            color: white;
            margin-left: 30px;
            font-size: 28px;

        }

        Ul#header {
            margin: 20px 0px 0px 0px;
            height: 42px;
            width: 960px;
        }

        h2 {
            margin: 0px 0px 0px 0px;
            padding: 0px 0px 0px 0px;
            height: 72px;
            font-size: 60px;
            font-family: monospace;
        }

        #footer,
        a {

            vertical-align: top;
            color: rgb(14, 81, 126);
            text-align: center;
            padding: 5px 30px 5px 0px;
            font-size: 18px;
        }




        #footer {
            background-color: rgb(210, 230, 248);

            border-radius: 10px;
            margin-top: 40px;


        }

        .spans {
            color: rgb(23, 95, 179);
        }

        #icon001 {
            height: 68px;
            width: 68px;
        }


        @-webkit-keyframes bounce {

            from,
            20%,
            53%,
            80%,
            to {
                -webkit-animation-timing-function: cubic-bezier(0.215, 0.61, 0.355, 1);
                animation-timing-function: cubic-bezier(0.215, 0.61, 0.355, 1);
                -webkit-transform: translate3d(0, 0, 0);
                transform: translate3d(0, 0, 0);
            }

            40%,
            43% {
                -webkit-animation-timing-function: cubic-bezier(0.755, 0.05, 0.855, 0.06);
                animation-timing-function: cubic-bezier(0.755, 0.05, 0.855, 0.06);
                -webkit-transform: translate3d(0, -30px, 0);
                transform: translate3d(0, -30px, 0);
            }

            70% {
                -webkit-animation-timing-function: cubic-bezier(0.755, 0.05, 0.855, 0.06);
                animation-timing-function: cubic-bezier(0.755, 0.05, 0.855, 0.06);
                -webkit-transform: translate3d(0, -15px, 0);
                transform: translate3d(0, -15px, 0);
            }

            90% {
                -webkit-transform: translate3d(0, -4px, 0);
                transform: translate3d(0, -4px, 0);
            }
        }

        @keyframes bounce {

            from,
            20%,
            53%,
            80%,
            to {
                -webkit-animation-timing-function: cubic-bezier(0.215, 0.61, 0.355, 1);
                animation-timing-function: cubic-bezier(0.215, 0.61, 0.355, 1);
                -webkit-transform: translate3d(0, 0, 0);
                transform: translate3d(0, 0, 0);
            }

            40%,
            43% {
                -webkit-animation-timing-function: cubic-bezier(0.755, 0.05, 0.855, 0.06);
                animation-timing-function: cubic-bezier(0.755, 0.05, 0.855, 0.06);
                -webkit-transform: translate3d(0, -30px, 0);
                transform: translate3d(0, -30px, 0);
            }

            70% {
                -webkit-animation-timing-function: cubic-bezier(0.755, 0.05, 0.855, 0.06);
                animation-timing-function: cubic-bezier(0.755, 0.05, 0.855, 0.06);
                -webkit-transform: translate3d(0, -15px, 0);
                transform: translate3d(0, -15px, 0);
            }

            90% {
                -webkit-transform: translate3d(0, -4px, 0);
                transform: translate3d(0, -4px, 0);
            }
        }

        .bounce {
            -webkit-animation-name: bounce;
            animation-name: bounce;
            -webkit-transform-origin: center bottom;
            transform-origin: center bottom;
        }


        #icon001 {
            /* This section calls the slideInFromrightt animation we defined above */
            animation: 1s ease-out .3s 20 bounce;
        }
    </style>

</head>

<body>

    <div class="jumbotron">
        <h2>Elvis's <span class="spans">Portfolio</span></h2>

        <Ul id="header">
            <a href="{% url 'quotes:home' %}">
                <li> <span class="spans">
                        Home
                    </span></li>
            </a>
            <a href="{% url 'quotes:about' %}">
                <li> <span class="spans">
                        Aboutme
                    </span></li>
            </a>

            <a href="{% url 'quotes:python' %}">
                <li> Python/Django </li>
            </a>
            <a href="{% url 'quotes:csharp' %}">
                <li>C#/ASP.NETcore </li>
            </a>
        </Ul>
        <a href="{% url 'quotes:python' %}">
            <img id="icon001" src='{% static "quotes/images/python.png" %}' alt="python"></a>
    </div>
    <div class='container-fluid'>

        {% block content %}{% endblock content %}
        <footer class="fixed-bottom">

            <div id="footer">
                <a href="{% url 'quotes:home' %}"> Home </a>
                <a href="{% url 'quotes:about' %}"> About </a>
                <a href="{% url 'quotes:python' %}"> Python/Django</a>
                <a href="{% url 'quotes:csharp' %}"> C#/ASP.NETcore<a>
                        <a href="{% url 'quotes:contact' %}"> Contact</a>


            </div>


        </footer>


        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
            crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"
            integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut"
            crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"
            integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k"
            crossorigin="anonymous"></script>
</body>

</html>

apps/quotes/templates/quotes/edit.html
{% extends "quotes/base.html" %}

{% block title %} Edit {% endblock title %}

{% block content %}

<h3>Hello {{ user.first_name }} {{ user.last_name }} ! Lets edit your quote </h3>

<a href="{% url 'users:logout' %}" class="button">
    <h4>Logout</h4>
</a>
<a href="{% url 'quotes:index'  %}" class="button">
    <h4>Goback</h4>
</a>
<hr>


{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}
<form action="{% url 'quotes:update' quote.id%}" method='post'>
    {% csrf_token %}
    <div class="form-group">
        <p> <label for="name">Author of your Quote :</label> </p>
        <P> <input type="text" class="form-control" name="author" value="{{ quote.author }}">
        </p>
    </div>

    <div class="form-group">
        <p><label for="quote">Quote:</label></p>
        <textarea name="quote" id="" cols="60" rows="5">"{{ quote.quote }}"</textarea>
    </div>



    <input class="form-control" type="submit" value="edit">


</form>
{% endblock content %}

apps/quotes/templates/quotes/quotes.html
{% extends "quotes/base.html" %}

{% block title %}
quotes
{% endblock title %}


{% block content %}



<h1> Welcome {{ user.first_name }} {{ user.last_name }}! </h1><br>
<h3> You have Successfully Logged In! </h3><br>
<hr>


<a href="{% url 'users:edit' user.id %}" class="button">
    <h4>Edit My Account</h4>
</a>
<a href="{% url 'users:logout'  %}" class="button">
    <h4>Logout</h4>
</a>
<hr>


<h1>Write a favorite Quote! </h1><br>
<h1>-You can delete or edit only your own quotes.
</h1><br>
<h1>-You can't like or unlike your own quotes only other users can.</h1><br>
<h1>-See how popular your quotes are </h1><br>
<h1>-You are encouraged to like other users quotes that pick your ineterets. </h1><br>
<h1>-Select your first name beside your posts to view posts by all users</h1><br>
<br>
<hr>



{%for quote in quotes%}
<h3>Author: {{ quote.author}}</h3>
<h3>Quote: {{ quote.quote}}</h3>
<h3>Posted by : <a href="{% url 'quotes:view' %}" role="link">{{ quote.creator.first_name }}</a>
    {{quote.likes.count }} |

    {%if user.id is quote.creator_id %}

    <a href="{% url 'quotes:edit' quote.id %}" class="button">Edit</a>|

    <form action="{% url 'quotes:delete' quote.id%}" method='post'>
        {% csrf_token %}
        <input type="submit" value="Delete">
    </form>

    {% else %}


    {%if user in quote.likes.all%}


    <a href="{% url 'quotes:unlike' quote.id %}" class="button">Unlike</a>

    {% else %}

    <a href="{% url 'quotes:like' quote.id %}" class="button">Like</a>|
    {%endif%}
</h3>
{%endif%} <br><br>
<hr>
{%endfor%}








{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}
<h1>Add a Quote</h1>
<form action="{% url 'quotes:create' %}" method='post'>
    {% csrf_token %}
    <div class="form-group">
        <p> <label for="author">Author:</label> </p>
        <P> <input type="text" class="form-control" name="author" placeholder=" authors name"> </p>
    </div>

    <div class="form-group">
        <p><label for="quote">Quote:</label></p>
        <textarea name="quote" id="" cols="60" rows="5"></textarea>
    </div>

    <input class="form-control" type="submit" value="Submit">

</form>




{% endblock content %}

apps/quotes/templates/quotes/view.html
{% extends "quotes/base.html" %}

{% block title %} View {% endblock title%}
{% block content %}


<a href="{% url 'quotes:index'  %}" class="btn btn-info" role="button">
    <h4>Goback</h4>
</a> <br>
<hr>

<h1> Quotes</h1> <br>
<hr>

{%for quote in quotes %}


<div class="resizequote">
    <h3>Author: {{ quote.author}}</h3>
    <h3>Quote: {{ quote.quote}}</h3> <br>
    <hr>


    {%endfor%}


</div>


{% endblock content %}